name: Release Game

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install LÖVE
        run: |
          sudo apt-get update
          sudo apt-get install -y love

      - name: Install love-release
        run: |
          sudo apt-get install -y luarocks libzip-dev
          sudo luarocks install love-release

      - name: Build releases
        run: |
          # Create releases for all platforms
          love-release -M --uti com.corp-ladder-game || true  # Mac
          love-release -W -a "Cline" -p "corp-ladder-game" || true  # Windows
          love-release -a "Cline" -p "corp-ladder-game" || true     # Linux
          
          # Rename files to match tag version
          VERSION=${GITHUB_REF#refs/tags/}
          cd releases
          for f in *; do
            mv "$f" "${f/0.1.0/$VERSION}" || true
          done

      - name: List Release Files
        run: ls -la releases/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
